/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import org.json.*;
import java.net.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import Reto1.*;
/**
 *
 * @author Alexandru
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private JSONObject currencyJSONObject;
    private SortedSet<String> currencyList;
    public GUI() {
        currencyList = new TreeSet<String>();
        currencyJSONObject = new JSONObject();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        try {
            getCurrenciesJSON();
            initComponents();
        } catch (Exception e) {
            System.out.println("Exception: " + e.getMessage());
        }
    }
    
    private void getCurrenciesJSON() throws Exception{
        URL currencyListURL = new URL("https://openexchangerates.org/api/currencies.json");
        HttpURLConnection con = (HttpURLConnection) currencyListURL.openConnection();
        con.connect();
        int status = con.getResponseCode();
        JSONObject json = null;
        switch (status) {
            case 200:
            case 201:
                BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = br.readLine()) != null) {
                    sb.append(line+"\n");
                }
                br.close();
                currencyJSONObject = new JSONObject(sb.toString());
        }
        Iterator<String> keysCurrencies = currencyJSONObject.keys();
        while (keysCurrencies.hasNext()) {
            currencyList.add(keysCurrencies.next());
        }
    }
    
    private ComboBoxModel getModelComboBoxes() {
        ComboBoxModel model = new DefaultComboBoxModel(currencyList.toArray());
        return model;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMonedaOrigen = new javax.swing.JTextField();
        comboBoxMonedaOrigen = new javax.swing.JComboBox<>();
        titleApp = new javax.swing.JLabel();
        jTextFieldMonedaDestino = new javax.swing.JTextField();
        comboBoxMonedaDestino = new javax.swing.JComboBox<>();
        botonConvertir = new javax.swing.JButton();
        titleMonedaOrigen = new javax.swing.JLabel();
        titleResultado = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(476, 200));
        setMinimumSize(new java.awt.Dimension(476, 200));
        setResizable(false);

        comboBoxMonedaOrigen.setModel(getModelComboBoxes());

        titleApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleApp.setText("Conversor de monedas");

        jTextFieldMonedaDestino.setEnabled(false);

        comboBoxMonedaDestino.setModel(getModelComboBoxes());

        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });

        titleMonedaOrigen.setText("Moneda origen (poner decimales con .):");

        titleResultado.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titleMonedaOrigen))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(titleResultado)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(titleApp)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleApp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleMonedaOrigen)
                    .addComponent(titleResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMonedaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMonedaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConvertir)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        try {
            // Redondeamos a 2 decimales.
            double res = Double.parseDouble(jTextFieldMonedaOrigen.getText()) * Conversor.getRate(comboBoxMonedaOrigen.getSelectedItem().toString(), comboBoxMonedaDestino.getSelectedItem().toString());
            res *= 100;
            res = Math.round(res);
            res /= 100;
            jTextFieldMonedaDestino.setText(res + "");
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_botonConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConvertir;
    private javax.swing.JComboBox<String> comboBoxMonedaDestino;
    private javax.swing.JComboBox<String> comboBoxMonedaOrigen;
    private javax.swing.JTextField jTextFieldMonedaDestino;
    private javax.swing.JTextField jTextFieldMonedaOrigen;
    private javax.swing.JLabel titleApp;
    private javax.swing.JLabel titleMonedaOrigen;
    private javax.swing.JLabel titleResultado;
    // End of variables declaration//GEN-END:variables
}
